steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cvid-api:$BRANCH_NAME', '.']
  # push the container image to Container Registry
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: /bin/sh
  args:
  - "-c"
  - |
    cat << EOF > secret.yaml
    env_variables:
      MONGO_DSN: $_MONGO_DSN
    EOF
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/cvid-api']
  # deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy','secret.yaml', '--allow-unauthenticated']
  env:
  - 'PORT=8080'
images:
- gcr.io/$PROJECT_ID/cvid-api